Enhance `me` command to change profile picture
AY1920S2-CS2103T-F10-1/main pull request #135
Opened 2020-03-26 12:25 UTC by nhamhung

I added a DisplayPicture class as a Field inside Person class. It takes in the file path to that file.

Also, also update CommandResult a bit.

Also, touch up on UI.

2020-03-26 12:46 UTC, helloImHai approved these changes
Nice one bro 🥇
I like the changing of names and but be careful of "/"

2020-03-26 13:10 UTC, chrisjwelly requested changes
Changes in logic looks good to me! Note the point on String equality :)

I am not familiar with FXML, so I shall let others comment on that?

2020-03-26 13:10 UTC, chrisjwelly commented on src/main/java/seedu/address/logic/commands/CommandResult.java
> +        return dataToUser == "";
I'm not sure if this will work as for Strings, we should use the `equals` method.

Perhaps `dataToUser.equals("")` would be better?

2020-03-26 13:10 UTC, chrisjwelly commented on src/main/java/seedu/address/logic/commands/EditUserCommand.java
> +            + PREFIX_DP + "/Users/nhamquochung/Desktop/test.png "
I can't think of a better way than hardcoding this path, but we should be careful here when others will be testing our app

2020-03-28 13:59 UTC, helloImHai approved these changes
As it should be m8 💯💯💯

2020-03-28 14:01 UTC, merged