Add model tests
AY1920S2-CS2103T-F10-1/main pull request #253
Opened 2020-04-06 17:02 UTC by duongphammmm

Add tests for all item types and fields.

2020-04-06 18:21 UTC, wardetu requested changes
Looks alright.

Needs some fixes regarding where the test methods go.

2020-04-06 18:21 UTC, wardetu commented on src/test/java/seedu/address/model/item/field/TimeTest.java
> +        assertThrows(NullPointerException.class, () -> Time.isValidTime(null));
This should be in a different test method since it tests for exception and not proper return values.

2020-04-06 18:21 UTC, wardetu commented on src/test/java/seedu/address/model/item/field/GithubTest.java
> +        assertThrows(NullPointerException.class, () -> Github.isValidGithub(null));
Put this method in an `isValidGithub_nullInput_throwsNullPointerException()` method.

2020-04-07 09:46 UTC, helloImHai approved these changes
As it should be m8 💯💯💯

2020-04-07 09:46 UTC, merged