Add rgen test
AY1920S2-CS2103T-F10-1/main pull request #254
Opened 2020-04-06 17:52 UTC by duongphammmm

2020-04-06 18:29 UTC, wardetu approved these changes
LGTM!

2020-04-07 03:12 UTC, helloImHai requested changes
Since you're already doing the tests for rgen can you also add the test for rgen parser?

2020-04-07 09:52 UTC, helloImHai approved these changes
Nice one bro 🥇Except for that 1 convention change? I'll approve, real quick change then can self-merge!

2020-04-07 09:52 UTC, helloImHai commented on src/main/java/seedu/address/logic/parser/GenerateResumeCommandParser.java
> +            throw new ParseException(GenerateResumeCommand.MESSAGE_USAGE);
I think the new convention is that we'll wrap this around a "Invalid Command Format!\n...." can look at my PR to see? Not all but whenever we call the XYZ.Command.MESSAGE_USAGE it's quite clear

2020-04-07 10:44 UTC, merged