Add tests for edit internship and project
AY1920S2-CS2103T-F10-1/main pull request #285
Opened 2020-04-10 05:23 UTC by nhamhung

One part I'm not sure how to test: If we edit an item into another with the same name in the item list -> then DuplicateItemException should be thrown.

2020-04-10 05:25 UTC, nhamhung commented on src/test/java/seedu/address/logic/commands/edit/EditInternshipCommandTest.java
> +        modelStub.addInternship(sampleEditedInternship);
This part i tried assertThrows exception but it does not throw and the modelStub just edit the first Internship into a duplicate of the second Internship

2020-04-10 05:26 UTC, nhamhung commented on src/test/java/seedu/address/logic/commands/edit/EditInternshipCommandTest.java
> +        modelStub.addInternship(sampleEditedInternship);
And I don't include this @Test in Skill, Project and Resume yet! Just put here as a consideration

2020-04-11 11:15 UTC, helloImHai requested changes
Nice one bro 🥇
Give the document a quick glance for typos, remove the equals(), and remove the setABC(null) and I think it's ready to merge

2020-04-11 11:15 UTC, helloImHai commented on src/main/java/seedu/address/logic/commands/edit/EditSkillDescriptor.java
> +                && getLevel().get().getLevelCode() == e.getLevel().get().getLevelCode()
This line is not safe bc get() can return null

2020-04-11 11:15 UTC, helloImHai commented on src/test/java/seedu/address/logic/commands/edit/EditNoteCommandTest.java
> +        assertThrows(NullPointerException.class, () -> new EditInternshipCommand(null, null));
EditNoteCommand

2020-04-11 11:15 UTC, helloImHai commented on src/test/java/seedu/address/testutil/EditProjectDescriptorBuilder.java
> +     * Returns an {@code EditInternshipDescriptor} with fields containing {@code internship}'s details
Project

2020-04-11 11:15 UTC, helloImHai commented on src/test/java/seedu/address/testutil/EditResumeDescriptorBuilder.java
> +     * Returns an {@code EditInternshipDescriptor} with fields containing {@code internship}'s details
Resume

2020-04-11 11:15 UTC, helloImHai commented on src/test/java/seedu/address/logic/commands/edit/EditProjectCommandTest.java
> +        editProjectDescriptor.setTags(null);
Might want to remove this?

2020-04-11 11:27 UTC, nhamhung commented
> One part I'm not sure how to test: If we edit an item into another with the same name in the item list -> then DuplicateItemException should be thrown.

2020-04-11 12:23 UTC, chrisjwelly reviewed
LGTM! :tada:

But gotta make Hai's fixes first

2020-04-11 13:09 UTC, helloImHai approved these changes
All fine and dandy 💃💃

2020-04-11 13:09 UTC, merged