Update ui for text overflow
AY1920S2-CS2103T-F10-1/main pull request #336
Opened 2020-04-12 10:49 UTC by nhamhung

1. Bring back the scroll bars
2. Text overflow will print "..."

2020-04-12 16:08 UTC, helloImHai commented on src/main/resources/view/DarkTheme.css
> +.scroll-bar {
LOL WHAT THE =))))

2020-04-12 16:12 UTC, helloImHai requested changes
Please play around with the UI more when you make changes, I like some of the changes but it breaks things.
<img width="1103" alt="Screenshot 2020-04-13 at 12 12 49 AM" src="https://user-images.githubusercontent.com/50471593/79073877-8bb97e80-7d1b-11ea-8767-97f220ab0172.png">

2020-04-12 16:12 UTC, helloImHai commented on src/main/resources/view/DarkTheme.css
> +
LOL WHAT THEE NQH

2020-04-13 02:28 UTC, helloImHai approved these changes
As it should be m8 💯💯💯

2020-04-13 02:29 UTC, merged

2020-04-13 03:13 UTC, nhamhung commented on src/main/resources/view/DarkTheme.css
> +
Sorry~~